/* 🤖 this file was generated by svg-to-ts*/
export * from './build/deeIcons-compass.icon';
export * from './build/deeIcons-dashboard.icon';
export * from './build/deeIcons-medal.icon';
export * from './build/deeIcons-music.icon';
export * from './build/deeIcons-picture.icon';
export * from './build/deeIcons-shield.icon';
export * from './build/completeIconSet';
export * from './build/dee-icons.model';
